on:
  workflow_dispatch:
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to Fly
        uses: superfly/flyctl-actions@1.1
        with:
          args: "deploy --app ${{ secrets.STAGING_APP_NAME }} --build-arg FONT_AWESOME_TOKEN=${{ secrets.FA_TOKEN }}"
